repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(docs/|test\.sh$|README_.*\.md$|TODO_.*\.md$)
      - id: end-of-file-fixer
        exclude: ^(docs/|test\.sh$|README_.*\.md$|TODO_.*\.md$)
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.5
    hooks:
      - id: clang-format
        types_or: [c++, c]

  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy
        language: system
        types: [c++]
        args: ["--extra-arg=-std=c++17", "--extra-arg=-Iincludes"]
